// Script file for testing

MAP = new_instance("java.util.HashMap", new_array("java.lang.Object", 0));

function fibbonacci(count) {
    n = new_array("java.lang.Integer", count);
    n[0] = 0;
    n[1] = 1;

    // Loop starts from 2 because 0 and 1 are already printed
    for (i = 2; i < count; i++) {
        n[i] = n[i - 1] + n[i - 2];
    }

    return n;
}

function factorial_i(n) {
    rv = 1;
    while (n != 1) {
        rv *= n--;
    }
    return rv;
}

function factorial_r(n) {
    if (n == 1) return 1;
    else return n * factorial_i(--n);
}

LIST = new_instance("java.util.ArrayList", new_array("java.lang.Object", 0));

function adder(elt) {
    LIST.add(elt);
}

function main() {
    list = new_instance("java.util.ArrayList", new_array("java.lang.Object", 0));

    for (i = 1; i <= 5; i++) {
        list.add("" + i);
    }

    list.forEach(this::adder);
}
