// Reflection
EMPTY_ARRAY_CLASSES = new_array("java.lang.Class", 0);
EMPTY_ARRAY_OBJECTS = new_array("java.lang.Object", 0);

// Multithreading
EXECUTOR_SERVICE = null;

{
    executor_class = class_for_name("java.util.concurrent.Executors");
    EXECUTOR_SERVICE = executor_class
        .getMethod("newCachedThreadPool", EMPTY_ARRAY_CLASSES)
        .invoke(executor_class, EMPTY_ARRAY_OBJECTS);
}

function async(fn_ref) {
    EXECUTOR_SERVICE.execute(fn_ref);
}
